import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Full-turn delivery","description":"","frontmatter":{"title":"Full-turn delivery"},"headers":[],"relativePath":"guides/full-turn-delivery.md","filePath":"guides/full-turn-delivery.md","lastUpdated":1774352049000}');
const _sfc_main = { name: "guides/full-turn-delivery.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="full-turn-delivery-phenodocs" tabindex="-1">Full-turn delivery (PhenoDocs) <a class="header-anchor" href="#full-turn-delivery-phenodocs" aria-label="Permalink to &quot;Full-turn delivery (PhenoDocs)&quot;">​</a></h1><p>A <strong>full turn</strong> finishes when work is <strong>merged</strong> to <strong><code>main</code></strong> or an approved <strong>release branch</strong>, is <strong>visible on GitHub</strong> (PR URLs), and ships <strong>changelog</strong>, <strong>version</strong> (when applicable), and <strong>docs</strong> updates.</p><h2 id="requirements" tabindex="-1">Requirements <a class="header-anchor" href="#requirements" aria-label="Permalink to &quot;Requirements&quot;">​</a></h2><ol><li><strong>≥1 merged PR</strong> per turn to <code>main</code> or <code>release/*</code> (several PRs per turn are fine for stacked work).</li><li><strong>GitHub visibility:</strong> record PR link(s) in the PR body and optionally in <code>CHANGELOG.md</code> under <strong>[Unreleased]</strong>.</li><li><strong>Changelog:</strong> update root <strong><code>CHANGELOG.md</code></strong> for user-facing doc site or workflow changes.</li><li><strong>Version:</strong> bump <strong><code>package.json</code></strong> <code>version</code> when releasing a tagged docs build or publishing a semver story; otherwise state <strong>“version: N/A”</strong> in the PR.</li><li><strong>Docs:</strong> run <strong><code>bun run build</code></strong> before merge when <code>docs/</code> or <code>.vitepress/</code> changed (see <a href="./tooling">Toolchains</a>).</li></ol><h2 id="commands" tabindex="-1">Commands <a class="header-anchor" href="#commands" aria-label="Permalink to &quot;Commands&quot;">​</a></h2><div class="language-bash vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">gh</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> pr</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> create</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --fill</span><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">   # or explicit title/body with changelog + version note</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">gh</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> pr</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> merge</span><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">             # after CI green</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">gh</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> pr</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> list</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --state</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> merged</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --limit</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> 5</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><h2 id="batch-planning-next-50" tabindex="-1">Batch planning (Next 50) <a class="header-anchor" href="#batch-planning-next-50" aria-label="Permalink to &quot;Batch planning (Next 50)&quot;">​</a></h2><p>Large planning batches use <strong>five parallel lanes (A–E)</strong> and <strong>ten waves (W1–W10)</strong> — <strong>50 tasks</strong> with explicit <strong>Depends</strong> edges so work is <strong>DAGified</strong>: never more than five concurrent tasks, but independent tasks within the same wave can run together. See <strong><a href="/planning/full-turn-next50-20260326">Full-turn Next 50</a></strong>.</p><h2 id="related" tabindex="-1">Related <a class="header-anchor" href="#related" aria-label="Permalink to &quot;Related&quot;">​</a></h2><ul><li><a href="/planning/full-turn-next50-20260326">Full-turn Next 50</a> — 50-item DAG batch (5 agents × 10 waves)</li><li><a href="/planning/rich-workspace-views">Rich workspace views</a> — product roadmap for views</li><li><a href="/views/">Workspace views</a> — changelog, commit log, WBS hubs</li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("guides/full-turn-delivery.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const fullTurnDelivery = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  fullTurnDelivery as default
};
