import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Worklogs","description":"","frontmatter":{},"headers":[],"relativePath":"index/worklogs.md","filePath":"index/worklogs.md","lastUpdated":1772197872000}');
const _sfc_main = { name: "index/worklogs.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="worklogs" tabindex="-1">Worklogs <a class="header-anchor" href="#worklogs" aria-label="Permalink to &quot;Worklogs&quot;">​</a></h1><p>Autogenerated by docs/scripts/generate-doc-index.sh</p><ul><li><a href="./../docs/index/worklogs">docs/index/worklogs.md</a></li><li><a href="./../docs/sessions/2026-02-26-cliproxy-thegent-agentapi-cleanup-pass/00_SESSION_OVERVIEW">docs/sessions/2026-02-26-cliproxy-thegent-agentapi-cleanup-pass/00_SESSION_OVERVIEW.md</a></li><li><a href="./../docs/sessions/2026-02-26-cliproxy-thegent-agentapi-reconcile-v2/00_SESSION_OVERVIEW">docs/sessions/2026-02-26-cliproxy-thegent-agentapi-reconcile-v2/00_SESSION_OVERVIEW.md</a></li><li><a href="./../docs/sessions/2026-02-26-cliproxy-thegent-agentapi-reconcile-v3/00_SESSION_OVERVIEW">docs/sessions/2026-02-26-cliproxy-thegent-agentapi-reconcile-v3/00_SESSION_OVERVIEW.md</a></li><li><a href="./../docs/sessions/2026-02-26-cliproxy-thegent-agentapi-reconcile/00_SESSION_OVERVIEW">docs/sessions/2026-02-26-cliproxy-thegent-agentapi-reconcile/00_SESSION_OVERVIEW.md</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("index/worklogs.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const worklogs = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  worklogs as default
};
