import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Specs","description":"","frontmatter":{},"headers":[],"relativePath":"index/specs.md","filePath":"index/specs.md","lastUpdated":1772197872000}');
const _sfc_main = { name: "index/specs.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="specs" tabindex="-1">Specs <a class="header-anchor" href="#specs" aria-label="Permalink to &quot;Specs&quot;">​</a></h1><p>Autogenerated by docs/scripts/generate-doc-index.sh</p><ul><li><a href="./../docs/index/specs">docs/index/specs.md</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("index/specs.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const specs = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  specs as default
};
