import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Planning","description":"","frontmatter":{},"headers":[],"relativePath":"index/planning.md","filePath":"index/planning.md","lastUpdated":1772197872000}');
const _sfc_main = { name: "index/planning.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="planning" tabindex="-1">Planning <a class="header-anchor" href="#planning" aria-label="Permalink to &quot;Planning&quot;">​</a></h1><p>Autogenerated by docs/scripts/generate-doc-index.sh</p><ul><li><a href="./../docs/governance/stacked-prs/02-wbs-and-dag">docs/governance/stacked-prs/02-wbs-and-dag.md</a></li><li><a href="./../docs/index/planning">docs/index/planning.md</a></li><li><a href="./../docs/roadmap/">docs/roadmap/index.md</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("index/planning.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const planning = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  planning as default
};
